title: "isoPOS iShare"
description: "LINE 官方帳號、美業經營管理、數位工具與產業知識"
lang: "zh-TW"
url: "https://isopossoft.github.io"
baseurl: "/isopos-ishare"
permalink: /articles/:title/
author:
  name: "isoPOS"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "isoPOS"
exclude:
  - README.md
